### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices,, cpu and cuda:O! 

### ISSUE THREAD

**Issue by cardenluo** [banodoco/Steerable-Motion#20]
![image](https://github.com/banodoco/Steerable-Motion/assets/133877069/0b133784-374d-4543-a3db-0a1a80ecf4c1)
![image](https://github.com/banodoco/Steerable-Motion/assets/133877069/83dad131-c03f-4021-83bd-748a8c0ea822)

**Comment by peteromallet** [comment]
Press Update all in Comfy Manager and it should fix this - you need the latest version of nodes

**Comment by cardenluo** [comment]
After upgrading, the problem still exists. Finally, it was found that it was caused by the upgrade of ComfyUI-AnimateDiff-Evolved. Returning to the previous version will solve the problem. Thanks a lot .
https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/issues/253

**Comment by peteromallet** [comment]
That's very strange, will investigate - but glad it worked!
