### ISSUE TITLE
Module Install Failure

### ISSUE THREAD

**Issue by scoobiekw** [banodoco/Steerable-Motion#7]
great potential, loving the demo. Using ComfyUI portable install. All dependencies install properly with manager. Steerable Motion install fails with Git error 128 using Search and the experimental git address method.

Windows 11, 2080ti

**Comment by scoobiekw** [comment]
log

D:\ComfyUI_windows_portable>pause
Press any key to continue . . . Total VRAM 11264 MB, total RAM 32649 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
### Loading: ComfyUI-Manager (V1.11.1)
### ComfyUI Revision: 1806 [69033081] | Released on '2023-12-11'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FizzleDorf Custom Nodes: Loaded
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\edge_line.py", line 1, in <module>
    from .util import common_annotator_call, img_np_to_tensor, img_tensor_to_np, skip_v1
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\util.py", line 1, in <module>
    from ..v1 import openpose_v1, midas
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\openpose_v1\__init__.py", line 6, in <module>
    from . import util
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\v1\openpose_v1\util.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: No module named 'matplotlib'
[comfy_mtb] | INFO -> loaded 55 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (7) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion\__init__.py", line 1, in <module>
    from .SteerableMotion import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion\SteerableMotion.py", line 6, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion module for custom nodes: No module named 'matplotlib'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.9 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by peteromallet** [comment]
Running "pip install matplotlib" in your terminal should fix it after you restart. Apologies, assumed that was included in Python - added it to the environment.

**Comment by niqodea** [comment]
@peteromallet FYI I am still getting matplotlib as missing dependency and I am resorting to installing it manually for now, where is the environment file located?

**Comment by peteromallet** [comment]
Ah, my bad, looks like I accidentally didn't pull this when pushing a new update - apologies, just figuring this stuff out. Added there.

**Comment by niqodea** [comment]
No worries! Yep, now I can see the requirements file, thank you!
